#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

message="$(cat "$1")"
requiredPattern="^US[0-9]+:\s+([a-z0-9]+( [a-z0-9]+)+)$"

if [[ $message =~ $requiredPattern ]]; then
  exit 0
else

    if [ -t 1 ]; then
    exec < /dev/tty
    fi

    echo "-------------------------------------------------------"
    echo "[🚨] Invalid commit message format! 😕"
    echo "-------------------------------------------------------"
    echo "[FORMAT]    : <ticket number>: <what was done>"
    echo "[EXAMPLE]   : US123456: This is a sample commit message"
    echo "-------------------------------------------------------"
    echo "Ticket number is missing from your commit"
    echo "[̣❌] $message"
    echo "-------------------------------------------------------"
    read -p "[❕] Enter ticket number (e.g., US123456): " ticketNumber
    # commitMessage="$ticketNumber: $message"
    commitMessage="$message"
    echo "-------------------------------------------------------"
    echo "Your new commit message is:"
    echo "[✅] $commitMessage"
    echo "-------------------------------------------------------"

    # Prompt for confirmation
    read -p "Press 'Enter' to commit or 'Ctrl+C' to cancel"

    # Stage changes with the new message
    echo "$commitMessage" > "$1"

    exit $?


fi
